### ISSUE TITLE
MYLOG definition

### ISSUE THREAD

**Issue by Botched1** [beegee-tokyo/RAK4631-Quick-Start-Examples#1]
Consider adding definition of MYLOG function in the examples, or instruction text. The RAK4631 platform.io examples will not compile without that definition, and it may not be obvious to everyone where to get/how to define that function.

**Comment by beegee-tokyo** [comment]
As mentioned in the README, this is no longer maintained
![image](https://user-images.githubusercontent.com/512690/180342385-0247747b-57c0-492e-a568-c9d6a84baec1.png)

Maybe you want to checkout the [WisBlock-API](https://github.com/beegee-tokyo/WisBlock-API)
